import {pages,state,api,write,manager,can,esc,date,card,empty,field,area,select,btn,nav,modal,toast,navigate,query,errorView,all} from './core.js';
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${heads.length}">暂无数据</td></tr>`}</tbody></table></div>`;
const values=form=>Object.fromEntries(form);
const del=(path,row)=>api(path+'/'+row.id,{method:'DELETE',headers:{'If-Match':`"v${row.version}"`}});
const statuses=[['ACTIVE','启用'],['INACTIVE','停用']];
const optionRow=(items,button)=>items.map(x=>[x.id,button(x)]);
function filterBar(extra=''){return `<form data-action="search" class="toolbar">${field('关键词','q','','search')}${extra}<button type="submit" class="primary">查询</button>${btn('刷新','reload')}</form>`;}
async function crudList(ctx,{path,heads,row,create,edit,extra='',filter=''}){
  let page=1,params={},items=[];
  ctx.set(card(filterBar(filter)+`<div class="toolbar">${create?btn('新增','new','class="primary"'):''}${extra}</div><div id="data-table"></div>`));
  async function load(){const data=await api(path+query({...params,page,page_size:20}));if(!ctx.active())return;items=data.items;document.querySelector('#data-table').innerHTML=table(heads,items.map(row))+`<div class="pagination">共 ${data.total} 条 ${btn('上一页','prev',page===1?'disabled':'')} ${page} ${btn('下一页','next',page*20>=data.total?'disabled':'')}</div>`;}
  ctx.on('search',async form=>{params=values(new FormData(form));page=1;await load();});ctx.on('reload',load);ctx.on('prev',async()=>{page--;await load();});ctx.on('next',async()=>{page++;await load();});
  if(create)ctx.on('new',()=>create(load));if(edit)ctx.on('edit',b=>edit(items.find(x=>x.id===b.dataset.id),load));
  await load();return {load,get:id=>items.find(x=>x.id===id)};
}
pages.set('persons',async ctx=>{
  const fields=x=>field('人员编号（不可修改）','person_code',x?.person_code||'','text',x?'disabled':'required pattern="[A-Za-z0-9_-]{1,32}" maxlength="32"')+field('姓名（虚拟业务档案）','name',x?.name||'','text','required maxlength="50"')+area('关注原因 / 备注','attention_note',x?.attention_note||'','maxlength="1000"')+select('状态','status',statuses,x?.status||'ACTIVE')+field('档案照片（JPEG / PNG，最大10MiB）','photo','','file','accept="image/png,image/jpeg"')+(x?.photo_media_id?'<label class="check"><input name="remove_photo" type="checkbox">移除当前照片</label>':'');
  const save=async(data,x)=>{const body={name:data.get('name'),attention_note:data.get('attention_note'),status:data.get('status')};const file=data.get('photo');if(file?.size){const form=new FormData();form.append('file',file);form.append('purpose','PERSON_PHOTO');body.photo_media_id=(await api('/media',{method:'POST',body:form})).id;}else if(data.has('remove_photo'))body.photo_media_id=null;if(x)await write('/persons/'+x.id,{...body,expected_version:x.version},'PATCH');else await write('/persons',{...body,person_code:data.get('person_code')});};
  const list=await crudList(ctx,{path:'/persons',heads:['编号','姓名','状态','关注原因','更新','操作'],row:x=>[esc(x.person_code),esc(x.name),x.status==='ACTIVE'?'启用':'停用',esc(x.attention_note),date(x.updated_at),manager()?btn('编辑','edit',`data-id="${x.id}"`)+btn('删除','delete',`data-id="${x.id}"`):'只读'],filter:select('状态','status',[['','全部'],...statuses]),create:manager()?load=>modal('新增虚拟人员档案',fields(),async d=>{await save(d);await load();}):null,edit:manager()?(x,load)=>modal('编辑档案',fields(x),async d=>{await save(d,x);await load();}):null});
  ctx.on('delete',b=>{const x=list.get(b.dataset.id);modal('删除档案','<p>删除后不能新关联该档案；既有检测记录中的人工关联快照保留。</p>',async()=>{await del('/persons',x);await list.load();},'确认删除');});
});
const permissions=['person.read','detection.camera','detection.image','detection.read','detection.review','chat.use','assistant.use'];
pages.set('users',async ctx=>{
  const list=await crudList(ctx,{path:'/admin/users',heads:['用户名','显示名称','角色','状态','操作'],row:u=>[esc(u.username),esc(u.display_name),esc(u.role),esc(u.status),btn('资料','edit',`data-id="${u.id}"`)+btn('密码','reset-password',`data-id="${u.id}"`)+btn('权限 / 状态','permissions',`data-id="${u.id}"`)+btn('删除','delete',`data-id="${u.id}"`)],create:load=>modal('创建用户',field('用户名','username','','text','required pattern="[A-Za-z0-9_]{3,32}"')+field('显示名称','display_name','','text','required maxlength="50"')+field('临时密码（12–128位）','temporary_password','','password','required minlength="12" maxlength="128"'),async data=>{await write('/admin/users',values(data));await load();}),edit:(u,load)=>modal('用户资料',field('显示名称','display_name',u.display_name,'text','required maxlength="50"'),async data=>{await write('/admin/users/'+u.id,{...values(data),expected_version:u.version},'PATCH');await load();})});
  ctx.on('reset-password',b=>{const u=list.get(b.dataset.id);modal('重置用户密码',field('新临时密码','temporary_password','','password','required minlength="12" maxlength="128"')+'<p class="notice">撤销此用户的所有会话，下次登录强制改密。</p>',async data=>{await write('/admin/users/'+u.id+'/password-reset',{...values(data),expected_version:u.version});await list.load();});});
  ctx.on('permissions',b=>{const u=list.get(b.dataset.id);modal('权限与状态',select('账户状态','status',[['ACTIVE','启用'],['DISABLED','停用']],u.status)+(state.user.role==='SUPER_ADMIN'?select('角色','role',[['USER','普通用户'],['ADMIN','管理员']],u.role):'')+(u.role==='USER'?'<div class="check-grid">'+permissions.map(p=>`<label class="check"><input type="checkbox" name="permissions" value="${p}" ${u.permissions.includes(p)?'checked':''}>${p}</label>`).join('')+'</div>':'')+'<p class="notice">变更立即撤销旧登录。图片上传、记录读取分别授权；只有上传权限时无法查询结果。</p>',async data=>{let version=u.version;let role=u.role;if(data.get('role')&&data.get('role')!==role){const r=await write('/admin/users/'+u.id+'/role',{role:data.get('role'),expected_version:version},'PUT');version=r.version;role=r.role;}if(u.status!==data.get('status')){const r=await write('/admin/users/'+u.id+'/status',{status:data.get('status'),expected_version:version},'PUT');version=r.version;}if(u.role==='USER'&&role==='USER'){await write('/admin/users/'+u.id+'/permissions',{permissions:data.getAll('permissions'),expected_version:version},'PUT');}await list.load();});});
  ctx.on('delete',b=>{const u=list.get(b.dataset.id);modal('删除账户',`<p>将逻辑删除 @${esc(u.username)} 并撤销其会话；不删除历史审计。</p>`,async()=>{await del('/admin/users',u);await list.load();},'确认删除');});
});
pages.set('providers',async ctx=>{
  const inputs=x=>`<div class="grid two">${x?'':select('厂商','provider',[['DEEPSEEK','DeepSeek'],['QWEN','千问 / 百炼']])}${field('配置名称','name',x?.name||'','text','required maxlength="100"')}${field('API 基础地址（HTTPS 白名单）','base_url',x?.base_url||'https://api.deepseek.com','url','required')}${field('模型名称（请从厂商控制台确认）','model',x?.model||'','text','required maxlength="100"')}${field('API Key'+(x?'（留空保留）':''),'api_key','','password',x?'maxlength="512"':'required maxlength="512"')}${field('最大输出 Token','max_output_tokens',x?.max_output_tokens||2048,'number','required min="256" max="4096"')}${field('每日调用次数上限','daily_request_limit',x?.daily_request_limit||100,'number','required min="1" max="1000"')}</div><p class="muted">仅 DeepSeek / 千问官方服务；不同地域密钥须匹配地址。温度在智能体中配置。保存不会调用云端，测试需再次明确确认。</p>`;
  const save=async(d,x)=>{const data=values(d);data.max_output_tokens=+data.max_output_tokens;data.daily_request_limit=+data.daily_request_limit;if(x){if(!data.api_key)delete data.api_key;data.expected_version=x.version;}await write('/admin/llm/providers'+(x?'/'+x.id:''),data,x?'PATCH':'POST');};
  const list=await crudList(ctx,{path:'/admin/llm/providers',heads:['配置名称','厂商 / 模型','验证状态','启用','操作'],row:x=>[esc(x.name),esc(x.provider)+'<br>'+esc(x.model),x.is_validated?'已测试 · '+(x.capabilities?.supports_stream?'真实流式':'完整缓冲'):'需要连接测试',x.enabled?'是':'否',btn('编辑','edit',`data-id="${x.id}"`)+btn('测试连接','test',`data-id="${x.id}"`)+btn(x.enabled?'停用':'启用','toggle',`data-id="${x.id}"`)],create:load=>modal('新增云端服务',inputs(),async d=>{await save(d);await load();}),edit:(x,load)=>modal('编辑云端服务',inputs(x),async d=>{await save(d,x);await load();})});
  ctx.on('test',b=>{
    const x=list.get(b.dataset.id);
    const dialog=modal('确认云端能力测试',`<p>将向 ${esc(x.provider)} / ${esc(x.model)} 发送固定测试文本，不含业务内容。测试会使旧验证失效并停用配置，成功后需显式启用。</p><pre>仅回复：连接测试成功。</pre>${select('正文协议','protocol',[['BUFFERED','非流式 · 等待完整正文'],['STREAM','流式 · 实际 SSE 正文']])}${select('温度参数','temperature_mode',[['RANGE','测试温度上下限'],['OMIT','不发送温度参数']])}${field('温度下限','temperature_min',0,'number','required min="0" max="2" step="0.1"')}${field('温度上限','temperature_max',2,'number','required min="0" max="2" step="0.1"')}<p class="notice test-cost">本次最多发送2次请求（上下限各1次），可能计费；任何一步失败立即停止，不自动重试或更换协议。边界测试不等于证明所有中间数值或业务答案都正确。</p>`,async data=>{
      const omit=data.get('temperature_mode')==='OMIT';
      const low=omit?null:Number(data.get('temperature_min')),high=omit?null:Number(data.get('temperature_max'));
      if(!omit&&low>high)throw new Error('温度下限不能超过上限');
      const r=await write('/admin/llm/providers/'+x.id+'/test',{consent_to_test:true,expected_version:x.version,test_stream:data.get('protocol')==='STREAM',temperature_min:low,temperature_max:high});
      toast('能力测试通过，实际发送 '+r.test_call_count+' 次；请显式启用配置。');await list.load();
    },'同意所选测试与费用');
    const update=()=>{const omit=dialog.querySelector('[name=temperature_mode]').value==='OMIT';const low=dialog.querySelector('[name=temperature_min]'),high=dialog.querySelector('[name=temperature_max]');low.disabled=high.disabled=omit;const count=omit||low.value===high.value?1:2;dialog.querySelector('.test-cost').textContent='本次最多发送'+count+'次固定文本请求，可能计费；失败立即停止，不自动重试。边界验证不是所有中间数值或业务正确性的证明。';};
    dialog.addEventListener('input',update);dialog.addEventListener('change',update);update();
  });
  ctx.on('toggle',async b=>{const x=list.get(b.dataset.id);await write('/admin/llm/providers/'+x.id,{enabled:!x.enabled,expected_version:x.version},'PATCH');await list.load();});
});
pages.set('agents',async ctx=>{
  let providers=await all('/admin/llm/providers');
  const inputs=x=>field('智能体名称','name',x?.name||'','text','required maxlength="100"')+field('说明','description',x?.description||'','text','maxlength="500"')+select('关联厂商配置','provider_config_id',optionRow(providers,p=>p.name+' / '+p.model+(p.is_validated?' · 已测试':' · 未测试')),x?.provider_config_id||providers[0]?.id)+area('业务提示词（不能覆盖固定安全规则）','business_prompt',x?.business_prompt||'','required maxlength="4000"')+field('温度（模型不支持时留空）','temperature',x?x.temperature??'':0.7,'number','min="0" max="2" step="0.1"')+select('状态','status',statuses,x?.status||'INACTIVE')+'<p class="notice">智能体仅控制文字角色，不拥有执行系统操作的权限。高温度不代表准确。保存后旧预览需要重新准备确认。</p>';
  const save=async(d,x)=>{const data=values(d);data.temperature=data.temperature===''?null:+data.temperature;if(x)data.expected_version=x.version;await write('/admin/assistant/agents'+(x?'/'+x.id:''),data,x?'PATCH':'POST');};
  const list=await crudList(ctx,{path:'/admin/assistant/agents',heads:['角色','说明','温度','状态 / 版本','操作'],row:x=>[esc(x.name),esc(x.description),x.temperature??'不支持',esc(x.status)+' / v'+x.version,btn('编辑','edit',`data-id="${x.id}"`)+btn('设为默认','default',`data-id="${x.id}"`)+btn('归档','archive',`data-id="${x.id}"`)],extra:btn('清空默认角色','clear-default')+nav('管理云端服务 →','providers'),create:load=>{if(!providers.length){toast('请先保存厂商配置，再新增智能体');return;}modal('新增智能体',inputs(),async d=>{await save(d);await load();});},edit:(x,load)=>modal('编辑智能体',inputs(x),async d=>{await save(d,x);await load();})});
  const setDefault=async id=>{const settings=await api('/admin/settings/assistant');await write('/admin/settings/assistant',{default_agent_profile_id:id,expected_version:settings.version},'PUT');toast(id?'默认智能体已设置':'默认智能体已清空');};ctx.on('default',b=>setDefault(b.dataset.id));ctx.on('clear-default',()=>setDefault(null));ctx.on('archive',b=>{const x=list.get(b.dataset.id);modal('归档智能体','<p>归档后不能用于新请求；历史记录不删除。默认角色需先更换或清空。</p>',async()=>{await del('/admin/assistant/agents',x);await list.load();},'确认归档');});
});
pages.set('knowledge',async ctx=>{
  const fields=x=>field('标题','title',x?.title||'','text','required maxlength="100"')+area('业务资料正文（仅纯文本）','content',x?.content||'','required maxlength="10000" style="height:300px"')+select('状态','status',statuses,x?.status||'ACTIVE');
  const list=await crudList(ctx,{path:'/admin/knowledge/documents',heads:['标题','状态','版本','更新时间','操作'],row:x=>[esc(x.title),esc(x.status),x.version,date(x.updated_at),btn('查看 / 编辑','edit',`data-id="${x.id}"`)+btn('删除','delete',`data-id="${x.id}"`)],create:load=>modal('新增业务资料',fields(),async d=>{await write('/admin/knowledge/documents',values(d));await load();}),edit:(x,load)=>modal('编辑业务资料',fields(x),async d=>{await write('/admin/knowledge/documents/'+x.id,{...values(d),expected_version:x.version},'PATCH');await load();})});ctx.on('delete',b=>modal('删除资料','<p>删除后停止检索，依赖此来源的旧准备单将失效。</p>',async()=>{await del('/admin/knowledge/documents',list.get(b.dataset.id));await list.load();},'确认删除'));
});
pages.set('bigscreen',async ctx=>{
  ctx.set('<p class="notice">全站记录 / 检测框统计，不代表唯一人员或已确认嫌疑。UTC 分桶；误报不从原始框数扣除。</p><p id="freshness">正在获取服务端统计…</p><div id="metrics" class="metric-grid"></div>'+card('<div id="trends"></div>','最近24小时命中趋势（UTC小时桶）'));
  const labels={recent_hit_record_count:'近60秒命中记录',total_hit_record_count:'累计命中记录',detected_box_count:'累计检测框（含误报）',false_positive_record_count:'人工误报记录',user_total_count:'未删除账户（含停用）',online_user_count:'在线用户（去重）',agent_profile_count:'智能体（未归档）'};
  async function refresh(){try{const m=await api('/admin/dashboard/summary',{background:true});const end=new Date(m.as_of);const start=new Date(end-24*3600*1000);const t=await api('/admin/dashboard/trends'+query({from:start.toISOString(),to:end.toISOString(),bucket:'HOUR'}),{background:true});if(!ctx.active())return;document.querySelector('#freshness').textContent='最后成功更新：'+date(m.as_of)+' · 每5秒尝试刷新';document.querySelector('#metrics').innerHTML=Object.entries(labels).map(([k,l])=>card(`<span class="muted">${l}</span><strong class="metric">${m[k]}</strong>`)).join('');const max=Math.max(1,...t.items.map(x=>x.hit_record_count));document.querySelector('#trends').innerHTML=t.items.map(x=>`<div class="trend-row"><span>${esc(x.bucket_start.slice(5,16))} UTC</span><div class="trend-bar" style="width:${100*x.hit_record_count/max}%"></div><strong>${x.hit_record_count}</strong></div>`).join('');}catch(err){if(ctx.active())document.querySelector('#freshness').innerHTML=errorView(new Error('数据暂不可用／已陈旧；保留最后成功值。'+err.message));}}
  await refresh();ctx.poll(refresh,5000);
});
pages.set('operations',async ctx=>{
  const status=await api('/system/status');let page=1,params={},mode='operations';
  ctx.set(card(Object.entries(status).map(([k,v])=>`<span class="tag">${k} · ${v}</span>`).join(' ')+'<p class="muted">本地 YOLO 仅由部署者维护，不开放权重、路径或阈值的网页写入。</p>','系统健康')+card(`<form data-action="filter" class="filters">${select('日志类型','type',[['operations','运维记录'],['audit','操作审计']])}${field('开始时间','created_from','','datetime-local')}${field('结束时间','created_to','','datetime-local')}${field('事件类型 / 审计动作','action')}${field('请求编号','request_id','','text','maxlength="36"')}${field('操作人 ID（审计）','actor_id')}${select('级别（运维）','level',[['','全部'],['INFO','信息'],['WARN','警告'],['ERROR','错误']])}<button class="primary" type="submit">查询</button></form><div id="log-table"></div>`));
  async function load(){const data=await api(mode==='audit'?'/admin/audit-logs'+query({...params,page}):'/admin/operations/logs'+query({...params,page}));if(!ctx.active())return;document.querySelector('#log-table').innerHTML=table(['时间','级别 / 动作','模块 / 对象','请求编号','脱敏上下文'],data.items.map(x=>[date(x.created_at),esc(x.level||x.action)+(x.event_code?'<br>'+esc(x.event_code):''),esc(x.module||x.object_type)+'<br>'+esc(x.object_id||''),esc(x.request_id||'—'),esc(JSON.stringify(x.safe_context||{before:x.before,after:x.after,outcome:x.outcome}))]))+`<div class="pagination">共 ${data.total} 条 ${btn('上一页','prev',page===1?'disabled':'')} ${page} ${btn('下一页','next',page*20>=data.total?'disabled':'')}</div>`;}
  ctx.on('filter',async form=>{const data=values(new FormData(form));mode=data.type;params={created_from:data.created_from?new Date(data.created_from).toISOString():'',created_to:data.created_to?new Date(data.created_to).toISOString():''};if(mode==='audit'){params.action=data.action;params.actor_id=data.actor_id;}else {params.level=data.level;params.event_code=data.action;}params.request_id=data.request_id;page=1;await load();});ctx.on('prev',async()=>{page--;await load();});ctx.on('next',async()=>{page++;await load();});await load();
});
pages.set('chatsearch',async ctx=>{
  const conversations=await all('/chat/conversations'),users=await all('/chat/users');let filters=null,page=1;
  const today=new Date(),yesterday=new Date(today-86400000),local=d=>new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);
  ctx.set('<p class="notice">只能检索本人当前加入的会话；不是全站私聊审计。CSV 包含聊天内容，下载后请妥善保管，撤权无法收回已下载文件。</p>'+card(`<form data-action="search" class="filters">${select('会话','conversation_id',[['','我加入的全部会话'],...conversations.map(c=>[c.id,c.title])])}${select('发送者','sender_id',[['','全部'],[state.user.id,'我'],...users.map(u=>[u.id,u.display_name])])}${field('关键词','q','','search','maxlength="100"')}${field('开始时间','created_from',local(yesterday),'datetime-local','required')}${field('结束时间','created_to',local(today),'datetime-local','required')}<div class="row"><button class="primary" type="submit">检索</button>${btn('导出 CSV','export')}</div></form><div id="chat-results">请选择条件查询（最多31天 / 导出10000条）。</div>`));
  function params(){const data=values(new FormData(document.querySelector('[data-action=search]')));for(const k of ['created_from','created_to']){if(!data[k])throw new Error('起止时间必填');data[k]=new Date(data[k]).toISOString();}return Object.fromEntries(Object.entries(data).filter(([,v])=>v!==''));}
  async function load(){const data=await api('/admin/chat/messages'+query({...filters,page}));if(!ctx.active())return;document.querySelector('#chat-results').innerHTML=table(['时间','会话','发送者','正文'],data.items.map(m=>[date(m.created_at),esc(conversations.find(c=>c.id===m.conversation_id)?.title||m.conversation_id),esc(m.sender_display_name),esc(m.content)]))+`<div class="pagination">共 ${data.total} 条 ${btn('上一页','prev',page===1?'disabled':'')} ${page} ${btn('下一页','next',page*20>=data.total?'disabled':'')}</div>`;}
  ctx.on('search',async()=>{filters=params();page=1;await load();});ctx.on('prev',async()=>{page--;await load();});ctx.on('next',async()=>{page++;await load();});ctx.on('export',()=>{const data=params();modal('导出聊天 CSV','<p>文件包含授权会话正文，请勿转发到未授权位置。最多31天、10000条，超限不会静默截断。</p>',async()=>{const response=await write('/admin/chat/exports',{...data,format:'CSV'},'POST',{raw:true});const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='chat-export.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},'确认下载');});
});
