import {pages,state,api,write,esc,date,card,empty,field,area,select,btn,nav,modal,toast,query,errorView,all} from './core.js';
import {markdown} from './markdown.js';
import {mountAvatar} from './avatar.js';
pages.set('assistant',async ctx=>{
  const [roles,conversations,avatar]=await Promise.all([api('/assistant/agents'),all('/assistant/conversations'),api('/system/avatar')]);
  const key='assistant-conversation:'+state.user.id,requestKey='assistant-request:'+state.user.id;
  let conversationId=sessionStorage.getItem(key),watching=false,lastAnswer='',streamAbort=null;
  if(!conversations.some(c=>c.id===conversationId))conversationId=conversations[0]?.id||null;
  ctx.set(`<div class="assistant-layout"><section class="avatar" id="avatar-root"><img src="/assets/digital-human-adult-male.png" alt="成年男性数字人占位展示"><p id="avatar-state" class="status-line">待机</p><p class="muted">${esc(avatar.fallback_label)}</p></section><section class="card"><h2>文字交流</h2><div class="grid two">${select('智能体角色','agent',roles.items.map(a=>[a.id,a.name+(a.available?'':'（暂不可用）')]),roles.default_agent_profile_id||roles.items[0]?.id||'')}${select('模式','mode',[['GENERAL','通用问答'],['KNOWLEDGE','实训知识查询'],['SUMMARY','事件摘要'],['REPORT','报告草稿']])}</div><div class="toolbar">${select('本人会话','conversation',[['','新会话'],...conversations.map(c=>[c.id,c.title||'未命名会话'])],conversationId||'')}${btn('新建会话','new-conversation')}</div><div id="assistant-history" class="chat-window"></div><form data-action="prepare" class="chat-compose"><div id="source-picker" hidden></div>${area('输入问题','question','','required maxlength="4000" placeholder="发送前会展示实际外发文本，确认后才调用云端"')}<button class="primary wide" type="submit" ${!roles.items.some(a=>a.available)?'disabled':''}>准备内容，预览后发送</button></form><div id="assistant-result"></div><div class="toolbar">${btn('停止生成','cancel-request','hidden')}${btn('复制最终回复','copy-answer','hidden')}</div>${roles.items.some(a=>a.available)?'':'<p class="notice">暂无可用智能体，请管理员先保存、测试并启用云端服务，然后配置角色。</p>'}</section></div>`);
  const disposeAvatar=await mountAvatar(document.querySelector('#avatar-root'),avatar);if(!ctx.active()){disposeAvatar();return;}ctx.dispose(disposeAvatar);
  const agent=document.querySelector('[name=agent]'),mode=document.querySelector('[name=mode]'),conv=document.querySelector('[name=conversation]'),result=document.querySelector('#assistant-result'),history=document.querySelector('#assistant-history');
  let currentId=sessionStorage.getItem(requestKey);
  const status=text=>{if(ctx.active())document.querySelector('#avatar-state').textContent=text;};
  const citationButtons=(id,items=[])=>items.length?'<div class="toolbar">'+items.map(x=>`<button type="button" class="link" data-action="citation" data-request="${esc(id)}" data-label="${esc(x.label)}">[${esc(x.label)}] ${esc(x.title||'查看来源')} · v${esc(x.version||'?')}</button>`).join('')+'</div>':'';
  async function loadHistory(){if(!conversationId){history.innerHTML=empty('选择角色并开始交流；不会自动外发。');return;}const expectedConversation=conversationId,expectedAgent=agent.value;const data=await api(`/assistant/conversations/${conversationId}/messages`+query({agent_profile_id:agent.value,page_size:100}),{background:true});if(!ctx.active()||conversationId!==expectedConversation||agent.value!==expectedAgent)return;const atBottom=history.scrollHeight-history.scrollTop-history.clientHeight<70;history.innerHTML=data.items.reverse().map(m=>m.hidden?'<p class="notice">来源权限已变化，此历史内容已隐藏。</p>':`<div class="message ${m.role==='USER'?'mine':''}"><small>${m.role==='USER'?'我':esc(m.agent_name_snapshot||'助手')} · ${date(m.created_at)}</small><div class="${m.role==='ASSISTANT'?'markdown':''}">${m.role==='ASSISTANT'?markdown(m.content):esc(m.content)}</div>${citationButtons(m.request_id,m.citations)}</div>`).join('')||empty('本角色暂无会话历史');if(atBottom)history.scrollTop=history.scrollHeight;}
  agent.onchange=()=>{loadHistory().catch(err=>toast(err.message));};conv.onchange=()=>{conversationId=conv.value||null;sessionStorage.setItem(key,conversationId||'');loadHistory().catch(err=>toast(err.message));};
  ctx.on('new-conversation',()=>{conversationId=null;conv.value='';sessionStorage.removeItem(key);loadHistory();});
  mode.onchange=async()=>{const picker=document.querySelector('#source-picker');picker.hidden=!['SUMMARY','REPORT'].includes(mode.value);if(!picker.hidden){try{const data=await api('/detections?page_size=100');picker.innerHTML='<h3>明确选择检测记录（最多10条）</h3><div class="checks">'+data.items.map(x=>`<label class="check"><input type="checkbox" name="detection" value="${x.id}">${esc(x.id.slice(0,8))} · ${esc(x.source)} · ${date(x.created_at)} · ${esc(x.state)}</label>`).join('')+'</div>';}catch(err){picker.innerHTML=errorView(err);}}};
  function final(data){if(!ctx.active())return;lastAnswer=data.answer||'';result.innerHTML=`<p class="status-line">${data.state==='SUCCEEDED'?'生成完成，需人工核验':'请求 '+esc(data.state)}${data.is_partial?' · 输出被截断，不是完整报告':''}</p>${data.answer?'<div class="markdown">'+markdown(data.answer)+'</div>'+citationButtons(data.id,data.citations):errorView(new Error(data.error_code||'本次生成未成功'))}<p class="muted">${esc(data.agent_name_snapshot||'')} / ${esc(data.provider||'')} / ${esc(data.model||'')} · ${esc(data.delivery_mode||'')} · 计费 ${esc(data.billing_state||'未知')}</p>`;document.querySelector('[data-action=copy-answer]').hidden=!lastAnswer;document.querySelector('[data-action=cancel-request]').hidden=true;status(data.state==='SUCCEEDED'?'回复完成':'生成未成功');}
  async function pollRequest(id){while(ctx.active()){const data=await api('/assistant/requests/'+id,{background:true});if(!ctx.active())return;if(['SUCCEEDED','FAILED','CANCELLED','EXPIRED'].includes(data.state)){final(data);await loadHistory();return;}result.innerHTML='<p class="status-line">'+esc(data.state)+' · 连接已转为查询原请求状态，不会再次调用云端</p>';await new Promise(r=>setTimeout(r,1000));}}
  async function watch(id){if(watching)return;watching=true;currentId=id;sessionStorage.setItem(requestKey,id);streamAbort=new AbortController();document.querySelector('[data-action=cancel-request]').hidden=false;status('云端处理中');let provisional='';
    try{const data=await api('/assistant/requests/'+id,{background:true});if(['SUCCEEDED','FAILED','CANCELLED','EXPIRED'].includes(data.state)){final(data);return;}result.innerHTML='<p class="status-line">'+esc(data.delivery_mode==='BUFFERED_FINAL'?'等待完整回复（非流式）':'处理中；业务证据模式只显示进度，正文校验后显示')+'</p>';const response=await api('/assistant/requests/'+id+'/events',{raw:true,background:true,signal:streamAbort.signal});const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(ctx.active()){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let index;while((index=buffer.indexOf('\n\n'))!==-1){const frame=buffer.slice(0,index);buffer=buffer.slice(index+2);const event=frame.split('\n').find(x=>x.startsWith('event:'))?.slice(6).trim();const line=frame.split('\n').find(x=>x.startsWith('data:'));if(!line)continue;const eventData=JSON.parse(line.slice(5));if(event==='status'){if(eventData.reset_required)provisional='';status(eventData.stage||eventData.state||'处理中');}if(event==='answer.delta'){provisional+=eventData.text;result.innerHTML='<p class="notice">生成中，尚未完成校验</p><div class="message">'+esc(provisional)+'</div>';}if(event==='answer.final'){provisional='';result.innerHTML='<div class="markdown">'+markdown(eventData.answer)+'</div>';}if(event==='error'){provisional='';result.innerHTML=errorView(new Error(eventData.message||eventData.code));}if(event==='done'){const doneData=await api('/assistant/requests/'+id,{background:true});final(doneData);await loadHistory();return;}}}if(ctx.active())await pollRequest(id);
    }catch(err){if(err.name==='AbortError')return;if(ctx.active()){result.innerHTML=errorView(err);if(![401,403,404].includes(err.status))try{await pollRequest(id);}catch(last){result.innerHTML=errorView(last);}}}finally{watching=false;}
  }
  ctx.dispose(()=>streamAbort?.abort());
  ctx.on('prepare',async form=>{if(watching)throw new Error('当前仍有生成请求，请等待或停止');const chosen=roles.items.find(x=>x.id===agent.value);if(!chosen?.available)throw new Error('请选择可用智能体');const data=new FormData(form);if(!conversationId){const c=await write('/assistant/conversations',{title:String(data.get('question')).slice(0,45)});conversationId=c.id;sessionStorage.setItem(key,c.id);const option=document.createElement('option');option.value=c.id;option.textContent=c.title;conv.append(option);conv.value=c.id;}status('本地准备中');const prepared=await write('/assistant/requests/prepare',{conversation_id:conversationId,agent_profile_id:agent.value,mode:mode.value,question:data.get('question'),detection_ids:['SUMMARY','REPORT'].includes(mode.value)?data.getAll('detection'):[]});status('等待外发确认');
    let confirmed=false;const dialog=modal('确认实际外发内容',`<p class="notice">以下完整文本将发往 ${esc(prepared.provider)} / ${esc(prepared.model)}。角色：${esc(prepared.agent_name_snapshot)} · 温度 ${esc(prepared.outbound_preview?.configuration?.temperature??'以冻结配置为准')}。可能计费。</p><p>准备单 ${esc(prepared.id)} · 有效至 ${date(prepared.expires_at)}</p><pre>${esc(JSON.stringify(prepared.outbound_preview,null,2))}</pre>`,async()=>{await write('/assistant/requests/'+prepared.id+'/confirm',{payload_hash:prepared.payload_hash,consent:true});confirmed=true;form.querySelector('textarea[name=question]').value='';watch(prepared.id).catch(err=>toast(err.message));},'确认发送给该厂商');dialog.addEventListener('close',()=>{if(!confirmed){write('/assistant/requests/'+prepared.id+'/cancel').catch(()=>{});status('已取消外发');}},{once:true});
  });ctx.on('cancel-request',async()=>{if(!currentId)return;const data=await write('/assistant/requests/'+currentId+'/cancel');streamAbort?.abort();final(data);toast('已停止等待；已经外发的请求可能计费。');});ctx.on('copy-answer',async()=>{if(navigator.clipboard)await navigator.clipboard.writeText(lastAnswer);else modal('复制文本',area('最终回复','copy',lastAnswer,'readonly'),async()=>{},'关闭');});
  const citationDialogs=new Map();
  ctx.dispose(()=>{for(const dialog of citationDialogs.keys())dialog.close();citationDialogs.clear();});
  ctx.on('citation',async button=>{
    const data=await api('/assistant/requests/'+button.dataset.request+'/citations/'+encodeURIComponent(button.dataset.label));
    if(!ctx.active())return;
    const dialog=modal('引用来源 ['+data.label+']',`<h3>${esc(data.title)}</h3><p>版本 ${esc(data.version)} · ${esc(data.type)}</p><pre>${esc(data.content||JSON.stringify(data.facts,null,2))}</pre><p class="notice">这里展示授权来源原文或检测事实，不代表AI解读已被人工确认。</p>`,async()=>{},'关闭');
    citationDialogs.set(dialog,button.dataset.request);dialog.addEventListener('close',()=>citationDialogs.delete(dialog),{once:true});
  });
  ctx.poll(async()=>{
    await loadHistory();
    for(const [dialog,id] of citationDialogs){try{await api('/assistant/requests/'+id,{background:true});}catch(err){if([401,403,404].includes(err.status)){dialog.close();toast('来源权限已变化，已关闭引用窗口。');}else throw err;}}
    if(!ctx.active()||watching||!currentId)return;
    try{await api('/assistant/requests/'+currentId,{background:true});}
    catch(err){if(!ctx.active())return;if([401,403,404].includes(err.status)){lastAnswer='';result.innerHTML=errorView(new Error('来源或访问权限已变化，旧答复已隐藏。'));document.querySelector('[data-action=copy-answer]').hidden=true;currentId=null;sessionStorage.removeItem(requestKey);}else throw err;}
  },5000);
  await loadHistory();if(currentId)watch(currentId).catch(err=>toast(err.message));
});
