import {pages,state,api,write,manager,can,esc,date,card,empty,field,area,btn,modal,toast,all,errorView,uuid} from './core.js';
import {mergeMessages} from './chat-history.js';
const emojis=['😀','😊','👍','✅','🙏','📌','⚠️','👋'];
async function mountChat(root,compact=false){
  let alive=true,selected=null,conversations=[],users=[],messages=[],presence=[],refreshing=false,publicRoom=null,sendId=null,hasOlder=false,selectionVersion=0;
  const owner=state.user.id;
  root.innerHTML=`<div class="chat-errors"></div><div class="toolbar"><span class="tag">同一部署内 · 真实账户</span>${manager()?'<button type="button" data-chat="create-group" class="primary">建立群聊</button>':''}<button type="button" data-chat="public">公共聊天室</button></div><div class="grid ${compact?'':'split'}"><section class="card"><h2>联系人与会话</h2><input class="contact-search" placeholder="搜索联系人 / 群聊" aria-label="搜索联系人"><div class="contact-list"></div></section><section class="card"><div class="toolbar"><h2 class="conversation-title">选择联系人</h2><span class="conversation-tools"></span></div><p class="presence muted"></p><div class="chat-window">选择其他用户、群聊，或主动加入公共聊天室。</div><form class="chat-compose" hidden><label>消息<textarea name="content" required maxlength="2000" placeholder="输入纯文本，Ctrl / ⌘ + Enter 发送"></textarea></label><div class="row"><div class="emoji-tools">${emojis.map(x=>`<button type="button" data-chat="emoji" data-emoji="${x}" aria-label="插入 ${x}">${x}</button>`).join('')}</div><button type="submit" class="primary">发送</button></div></form></section></div>`;
  const list=root.querySelector('.contact-list'),windowEl=root.querySelector('.chat-window'),form=root.querySelector('form'),input=form.querySelector('textarea'),search=root.querySelector('.contact-search');
  const showError=err=>root.querySelector('.chat-errors').innerHTML=errorView(err);
  const olderButton=document.createElement('button');olderButton.type='button';olderButton.dataset.chat='older';olderButton.textContent='加载更早消息';olderButton.hidden=true;windowEl.before(olderButton);
  function drawSelection(){
    root.querySelector('.conversation-title').textContent=selected?.title||'选择联系人';
    root.querySelector('.conversation-tools').innerHTML=selected?((selected.type==='GROUP'&&manager()&&selected.state==='ACTIVE'?'<button type="button" data-chat="manage">管理群聊</button>':'')+(selected.type==='PUBLIC'?'<button type="button" data-chat="leave">退出公共房间</button>':'')):'';
    form.hidden=!selected||selected.state!=='ACTIVE';olderButton.hidden=!selected||!hasOlder;
  }
  function drawList(){const q=search.value.toLowerCase();const item=(id,title,sub,action)=>`<button class="contact ${selected?.id===id?'selected':''}" type="button" data-chat="${action}" data-id="${id}">${esc(title)}<small>${esc(sub)}</small></button>`;list.innerHTML=`<h3>其他用户</h3>${users.filter(u=>(u.username+u.display_name).toLowerCase().includes(q)).map(u=>item(u.id,u.display_name,'@'+u.username,'direct')).join('')||'<p class="muted">暂无匹配的其他用户</p>'}<h3>群聊</h3>${conversations.filter(c=>c.type==='GROUP'&&c.title.toLowerCase().includes(q)).map(c=>item(c.id,c.title,`${c.member_count} 名成员 · 未读 ${c.unread_count}${c.state==='DISSOLVED'?' · 已解散，只读':''}`,'select')).join('')||'<p class="muted">暂无群聊</p>'}<h3>私聊会话</h3>${conversations.filter(c=>c.type==='DIRECT'&&c.title.toLowerCase().includes(q)).map(c=>item(c.id,c.title,'未读 '+c.unread_count,'select')).join('')||'<p class="muted">暂无私聊</p>'}<h3>公共房间</h3>${publicRoom?.joined?item(publicRoom.id,publicRoom.title,'已主动加入 · 所有加入者可见历史','select'):'<button type="button" data-chat="public">查看加入说明</button>'}`;}
  function drawMessages(){const bottom=windowEl.scrollHeight-windowEl.scrollTop-windowEl.clientHeight<70;windowEl.innerHTML=messages.map(m=>`<div class="message ${m.sender_id===owner?'mine':''}"><small>${esc(m.sender_display_name)} · ${date(m.created_at)} · #${esc(m.seq)}</small>${esc(m.content)}</div>`).join('')||empty('暂无消息，发送第一条真实消息。');if(bottom)windowEl.scrollTop=windowEl.scrollHeight;root.querySelector('.presence').textContent='在线（近60秒心跳）：'+(presence.map(u=>u.display_name).join('、')||'暂无');}
  async function refresh(){if(refreshing||!alive||state.user?.id!==owner)return;refreshing=true;try{const [cs,us,pub]=await Promise.all([all('/chat/conversations',{background:true}),all('/chat/users',{background:true}),api('/chat/public-conversation',{background:true})]);if(!alive)return;conversations=cs;users=us;publicRoom=pub;drawList();if(selected){const current=cs.find(c=>c.id===selected.id);if(!current){selectionVersion++;selected=null;messages=[];presence=[];hasOlder=false;input.value='';sendId=null;windowEl.innerHTML=empty('会话已不可见，可能已退出或被移除');drawSelection();root.querySelector('.presence').textContent='';return;}selected=current;drawSelection();await loadMessages();}}finally{refreshing=false;}}
  async function loadMessages(){if(!selected)return;const id=selected.id,version=selectionVersion,last=messages.at(-1)?.seq;const [data,online]=await Promise.all([api(`/chat/conversations/${id}/messages?limit=100${last?'&after_seq='+last:''}`,{background:true}),api(`/chat/conversations/${id}/presence?page_size=100`,{background:true})]);if(!alive||selected?.id!==id||selectionVersion!==version)return;if(!last)hasOlder=data.has_more;messages=mergeMessages(messages,data.items);presence=online.items;drawMessages();drawSelection();if(messages.length&&!document.hidden){await write(`/chat/conversations/${id}/read`,{last_read_seq:messages.at(-1).seq},'PUT',{background:true});}}
  async function loadOlder(){if(!selected||!messages.length||!hasOlder)return;const id=selected.id,version=selectionVersion;const data=await api(`/chat/conversations/${id}/messages?limit=100&before_seq=${messages[0].seq}`);if(!alive||selected?.id!==id||selectionVersion!==version)return;const top=windowEl.scrollTop,height=windowEl.scrollHeight;messages=mergeMessages(messages,data.items);hasOlder=data.has_more;drawMessages();drawSelection();windowEl.scrollTop=top+windowEl.scrollHeight-height;}
  async function choose(id){const version=++selectionVersion;const candidate=await api('/chat/conversations/'+id);if(!alive||selectionVersion!==version)return;selected=candidate;messages=[];hasOlder=false;presence=[];sendId=null;input.value='';windowEl.innerHTML=empty('正在读取消息…');drawSelection();drawList();await loadMessages();if(alive&&selectionVersion===version)windowEl.scrollTop=windowEl.scrollHeight;}
  function inviteForm(title,exclude=[]){const contacts=users.filter(u=>!exclude.includes(u.id));return (title?field('群聊名称','title',title==='NEW'?'':title,'text','required maxlength="100"'):'')+'<h3>邀请联系人</h3><div class="checks">'+contacts.map(u=>`<label class="check"><input type="checkbox" name="member" value="${u.id}">${esc(u.display_name)} (@${esc(u.username)})</label>`).join('')+'</div><p class="muted">创建者自动加入；至少选择1位联系人；群上限50人。</p>';}
  root.addEventListener('click',async event=>{const b=event.target.closest('[data-chat]');if(!b)return;event.stopPropagation();if(b.disabled)return;b.disabled=true;try{
    const action=b.dataset.chat;
    if(action==='direct'){const c=await write('/chat/direct-conversations',{peer_user_id:b.dataset.id});await refresh();await choose(c.id);}
    if(action==='select')await choose(b.dataset.id);
    if(action==='older')await loadOlder();
    if(action==='emoji'){input.value+=b.dataset.emoji;input.focus();}
    if(action==='create-group')modal('建立群聊',inviteForm('NEW'),async data=>{const member_ids=data.getAll('member');if(!member_ids.length)throw new Error('请至少邀请一位联系人');const group=await write('/admin/chat/groups',{title:data.get('title'),member_ids});await refresh();await choose(group.id);toast('群聊已建立，所选联系人已加入。');},'确认建立');
    if(action==='public'){const pub=await api('/chat/public-conversation');if(pub.joined)await choose(pub.id);else modal('公共聊天室 · 历史可见性说明',`<p class="notice">${esc(pub.history_notice)}</p><label class="check"><input type="checkbox" required name="agree">我已了解并同意加入</label>`,async()=>{const c=await write('/chat/public-conversation/join',{acknowledge_history_visibility:true});await refresh();await choose(c.id);},'同意并加入');}
    if(action==='leave')modal('退出公共聊天室','<p>退出后将不能继续读取或导出该房间消息，之前发出的消息仍对房间成员可见。</p>',async()=>{await write('/chat/public-conversation/leave');selected=null;form.hidden=true;windowEl.innerHTML=empty('已退出公共聊天室');root.querySelector('.conversation-title').textContent='选择联系人';root.querySelector('.conversation-tools').innerHTML='';await refresh();},'确认退出');
    if(action==='manage')await manageGroup();
  }catch(err){showError(err);}finally{b.disabled=false;}});
  async function manageGroup(){const group=selected;const members=await all('/admin/chat/groups/'+group.id+'/members');const d=modal('群聊管理',field('群聊名称','title',group.title,'text','required maxlength="100"')+`<h3>当前成员</h3><div class="checks">${members.map(u=>`<label class="check"><input type="checkbox" name="remove" value="${u.id||u.user_id}">${esc(u.display_name)}（勾选移除）</label>`).join('')}</div>`+inviteForm('',members.map(u=>u.id||u.user_id))+'<label class="check"><input type="checkbox" name="dissolve">解散群聊（成员保留只读历史）</label>',async data=>{let version=group.version;if(data.has('dissolve')){await write('/admin/chat/groups/'+group.id+'/dissolve',{expected_version:version});}else{if(data.get('title')!==group.title){const x=await write('/admin/chat/groups/'+group.id,{title:data.get('title'),expected_version:version},'PATCH');version=x.version;}const add=data.getAll('member');if(add.length){const x=await write('/admin/chat/groups/'+group.id+'/members',{user_ids:add,expected_version:version});version=x.version;}for(const id of data.getAll('remove')){const x=await api(`/admin/chat/groups/${group.id}/members/${id}`,{method:'DELETE',headers:{'If-Match':`"v${version}"`}});version=x.version;}}await refresh();if(conversations.some(x=>x.id===group.id))await choose(group.id);},'保存群设置');}
  search.oninput=drawList;
  input.onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();form.requestSubmit();}};
  form.onsubmit=async e=>{e.preventDefault();e.stopPropagation();if(!selected||selected.state!=='ACTIVE'||!input.value.trim())return;const b=form.querySelector('[type=submit]');if(b.disabled)return;b.disabled=true;const content=input.value,id=selected.id;sendId=sendId||{id:uuid(),content};if(sendId.content!==content)sendId={id:uuid(),content};try{await write(`/chat/conversations/${id}/messages`,{client_message_id:sendId.id,content});if(selected?.id===id&&input.value===content)input.value='';sendId=null;root.querySelector('.chat-errors').textContent='';await loadMessages();}catch(err){showError(err);}finally{b.disabled=false;}};
  await refresh();const timer=setInterval(()=>{if(!alive||state.user?.id!==owner){clearInterval(timer);root.innerHTML='';return;}if(!document.hidden)refresh().catch(showError);},3000);
  return ()=>{alive=false;clearInterval(timer);};
}
pages.set('communications',async ctx=>{ctx.set('<div id="communications-root"></div>');const root=document.querySelector('#communications-root');const dispose=await mountChat(root);if(!ctx.active())dispose();else ctx.dispose(dispose);});
let quick=null,closeQuick=()=>{};
window.addEventListener('session-cleared',()=>{if(quick)closeQuick();});
window.addEventListener('open-communications',async()=>{if(!state.user||!can('chat.use'))return;if(quick){closeQuick();return;}quick=document.createElement('section');quick.className='quick-chat';quick.innerHTML='<div class="toolbar"><h2>快捷通讯</h2><button class="quick-close" type="button">关闭</button></div><div class="quick-content"></div>';document.body.append(quick);let dispose=()=>{};const target=quick;closeQuick=()=>{dispose();target.remove();if(quick===target)quick=null;};target.querySelector('.quick-close').onclick=closeQuick;try{dispose=await mountChat(target.querySelector('.quick-content'),true);if(!target.isConnected)dispose();}catch(err){target.querySelector('.quick-content').innerHTML=errorView(err);}});
let badgeBusy=false;
setInterval(async()=>{if(!state.user||state.restricted||!can('chat.use')){if(quick)closeQuick();return;}if(badgeBusy||document.hidden)return;badgeBusy=true;try{const cs=await all('/chat/conversations',{background:true});const badge=document.querySelector('#unread-badge');if(badge)badge.textContent=cs.reduce((n,c)=>n+c.unread_count,0);}catch{}finally{badgeBusy=false;}},5000);
