import {pages,state,api,write,can,manager,esc,date,card,empty,field,area,select,btn,nav,modal,toast,navigate,query,errorView,all,uuid} from './core.js';
const stateName={PENDING:'待调度',QUEUED:'排队中',RUNNING:'处理中',SUCCEEDED:'识别成功',FAILED:'识别失败',CANCELLED:'已取消',COMPLETED:'处理完成',NOT_APPLICABLE:'未检出',RETAINED:'已复核—保留记录',FALSE_POSITIVE:'已复核—误报'};
const terminal=s=>['SUCCEEDED','FAILED','CANCELLED'].includes(s);
const media=id=>'/api/v1/media/'+id+'/content';
const labels=boxes=>[...new Set((boxes||[]).map(box=>box.class_name).filter(Boolean))];
const summary=x=>x.state==='SUCCEEDED'?(x.boxes?.length?`检出 ${x.boxes.length} 个框（${labels(x.boxes).join('、')}）`:'未检出模型目标'):(stateName[x.state]||x.state);
function recordTable(items){return `<div class="table-wrap"><table><thead><tr><th>记录编号</th><th>来源</th><th>创建时间</th><th>检测结果</th><th>复核状态</th><th>操作</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.id.slice(0,8))}</td><td>${x.source==='CAMERA'?'摄像头':'图片'}${x.batch_id?' · 批次':''}</td><td>${date(x.created_at)}</td><td>${summary(x)}${x.error_code?'<br><small>'+esc(x.error_code)+'</small>':''}</td><td>${x.state==='SUCCEEDED'?(x.review_status==='PENDING'?'待复核':stateName[x.review_status]):'—'}</td><td>${nav('查看详情','records/'+x.id)}</td></tr>`).join('')||'<tr><td colspan="6">暂无记录</td></tr>'}</tbody></table></div>`;}
pages.set('dashboard',async ctx=>{
  const [metrics,records,status]=await Promise.all([api('/dashboard/summary'),api('/detections?review_status=PENDING&page_size=5'),api('/system/status')]);
  ctx.set(`<p class="muted">你好，${esc(state.user.display_name)} · ${date(metrics.as_of)}</p><div class="grid two">${card(`<p>选择并授权本机设备，逐帧送检，结果需人工复核。</p>${can('detection.camera')?nav('打开摄像头识别 →','camera'):''}`,'摄像头识别')}${card(`<p>点击或拖拽添加 1–10 张图片，提交后逐张查看真实结果。</p>${can('detection.image')?nav('上传图片 →','image'):''}`,'单图 / 批量识别')}</div><div class="metric-grid">${[['我的待复核',metrics.pending_review_count],['我的命中记录',metrics.total_hit_record_count],['我的检测框',metrics.detected_box_count],['我的误报记录',metrics.false_positive_record_count]].map(([t,n])=>card(`<span class="muted">${t}</span><strong class="metric">${n}</strong>`)).join('')}</div><p class="notice">统计仅限本人；检测记录和检测框不代表唯一人员或已确认嫌疑。</p>${card(recordTable(records.items),'最近待复核记录')}${card(Object.entries(status).map(([k,v])=>`<span class="tag">${esc(k)} · ${esc(v)}</span>`).join(' '),'服务状态')}`);
});
pages.set('records',async ctx=>{
  if(ctx.route.includes('/'))return recordDetail(ctx,ctx.route.split('/')[1]);
  let page=1,filter={};
  ctx.set(card(`<form data-action="filter" class="filters">${select('来源','source',[['','全部'],['IMAGE','图片'],['CAMERA','摄像头']])}${field('开始时间','created_from','','datetime-local')}${field('结束时间','created_to','','datetime-local')}${select('复核状态','review_status',[['','全部'],['PENDING','待复核'],['RETAINED','保留记录'],['FALSE_POSITIVE','误报'],['NOT_APPLICABLE','未检出 / 不适用']])}<div class="row"><button class="primary" type="submit">查询</button>${btn('重置','reset')}</div></form><div id="records-table"></div>`));
  async function load(){const data=await api('/detections'+query({...filter,page,page_size:20}));if(!ctx.active())return;document.querySelector('#records-table').innerHTML=recordTable(data.items)+`<div class="pagination">共 ${data.total} 条 ${btn('上一页','prev',page===1?'disabled':'')}<span>${page}</span>${btn('下一页','next',page*20>=data.total?'disabled':'')}</div>`;}
  ctx.on('filter',async form=>{filter=Object.fromEntries(new FormData(form));for(const k of ['created_from','created_to'])if(filter[k])filter[k]=new Date(filter[k]).toISOString();page=1;await load();});ctx.on('reset',()=>navigate('records'));ctx.on('prev',async()=>{page--;await load();});ctx.on('next',async()=>{page++;await load();});await load();
});
async function recordDetail(ctx,id){
  const row=await api('/detections/'+id);const history=await api('/detections/'+id+'/history');
  const canReview=can('detection.review')&&row.state==='SUCCEEDED'&&row.boxes.length;
  ctx.set(`<div class="toolbar">${nav('← 返回记录','records')}${canReview?btn('人工复核','review','class="primary"'):''}${!terminal(row.state)?btn('取消等待任务','cancel'):''}${manager()&&terminal(row.state)?btn('删除记录','delete','class="danger"'):''}</div>${card(`<p>完整编号：${esc(row.id)}</p><div class="row"><span class="tag">${summary(row)}</span><span>${date(row.finished_at)}</span><span>${esc(row.model_id)}</span></div>${row.warning_codes.map(x=>`<p class="notice">${x==='RENDERED_MEDIA_FAILED'?'检测已留档，带水印图片生成失败':esc(x)}</p>`).join('')}<div class="grid two">${row.source_media_id?`<div><h3>原图（模型输入）</h3><img class="preview" src="${media(row.source_media_id)}" alt="检测原图"></div>`:''}${row.rendered_media_id?`<div><h3>检测框 / 服务端水印派生图</h3><img class="preview" src="${media(row.rendered_media_id)}" alt="带检测框和业务水印的派生图"></div>`:''}</div>`,'检测详情')}${card(`<p class="muted">以下框为原始模型输出；人工关联不代表模型确认身份。</p>${row.boxes.map(b=>`<div class="card"><div class="row"><strong>框 ${b.box_index+1} · ${esc(b.class_name)} · ${b.confidence.toFixed(4)}</strong><small>${b.bbox.map(x=>x.toFixed(1)).join(', ')}</small></div><p>${b.person_link?`人工关联：${esc(b.person_link.name_snapshot)} (${esc(b.person_link.person_code_snapshot)})<br><small>操作人 ${esc(b.person_link.linked_by)} · ${date(b.person_link.linked_at)}</small>`:'尚未人工关联人员档案'}</p>${canReview&&can('person.read')?btn(b.person_link?'更正关联':'关联档案','link',`data-id="${b.id}"`)+(b.person_link?btn('解除关联','unlink',`data-id="${b.id}"`):''):''}</div>`).join('')||empty('本记录没有检测框')}`,'检测框与人工关联')}${card(`<div class="table-wrap"><table><thead><tr><th>操作</th><th>时间</th><th>操作人</th><th>意见</th><th>变更后</th></tr></thead><tbody>${history.items.map(x=>`<tr><td>${esc(x.type)}</td><td>${date(x.created_at)}</td><td>${esc(x.actor_id)}</td><td>${esc(x.comment)}</td><td>${esc(JSON.stringify(x.after))}</td></tr>`).join('')||'<tr><td colspan="5">暂无复核或关联变更</td></tr>'}</tbody></table></div>`,'复核及关联历史')}`);
  ctx.on('review',()=>modal('人工复核',select('结论','review_status',[['RETAINED','保留记录（不代表确认身份）'],['FALSE_POSITIVE','误报']])+area('复核意见','comment','','required maxlength="1000"'),async data=>{await write('/detections/'+id+'/review',{...Object.fromEntries(data),expected_version:row.version},'PUT');await navigate(ctx.route);}));
  ctx.on('link',async button=>{const persons=await all('/persons?status=ACTIVE');if(!persons.length){toast('没有启用中的人员档案，请先维护名单');return;}modal('人工关联检测框',select('人员档案','person_id',persons.map(x=>[x.id,x.person_code+' · '+x.name]))+area('关联说明','comment','','required maxlength="1000"'),async data=>{await write(`/detections/${id}/boxes/${button.dataset.id}/person-link`,{...Object.fromEntries(data),expected_version:row.version},'PUT');await navigate(ctx.route);});});
  ctx.on('unlink',button=>modal('解除人工关联','<p>解除当前框的关联，历史快照仍保留。</p>',async()=>{await api(`/detections/${id}/boxes/${button.dataset.id}/person-link`,{method:'DELETE',headers:{'If-Match':`"v${row.version}"`}});await navigate(ctx.route);},'确认解除'));
  ctx.on('delete',()=>modal('删除记录','<p>逻辑删除后，记录和媒体不再从业务页面可见；操作将被审计。</p>',async()=>{await api('/detections/'+id,{method:'DELETE',headers:{'If-Match':`"v${row.version}"`}});await navigate('records');},'确认删除'));
  ctx.on('cancel',async()=>{await write('/detections/'+id+'/cancel');await navigate(ctx.route);});
  if(!terminal(row.state))ctx.poll(async()=>{const latest=await api('/detections/'+id,{background:true});if(ctx.active()&&latest.state!==row.state)await navigate(ctx.route);},1200);
}
pages.set('image',async ctx=>{
  let files=[],batch=null;
  ctx.set(card(`<div class="toolbar">${select('识别模式','mode',[['single','单图识别'],['batch','批量识别（最多10张）']])}</div><input id="image-files" type="file" accept="image/png,image/jpeg" hidden><div class="dropzone" role="button" tabindex="0" id="dropzone">点击选择或拖拽 JPG / PNG 图片<br><small>每张 ≤10 MiB · 批次 ≤100 MiB · 上传后主动点击识别</small></div><div id="file-previews" class="preview-grid"></div><div class="toolbar" style="margin-top:20px">${btn('开始识别','detect','class="primary"')}${btn('清空选择','clear-files')}</div><div id="image-progress" aria-live="polite"></div>`)+card('<div id="batch-history">正在读取批次…</div>','已受理批次（刷新后可恢复）'));
  const picker=document.querySelector('#image-files'),zone=document.querySelector('#dropzone'),mode=document.querySelector('[name=mode]');
  mode.onchange=()=>{picker.multiple=mode.value==='batch';};
  const draw=()=>{document.querySelector('#file-previews').innerHTML=files.map((f,i)=>`<figure><img src="${f.url}" alt="${esc(f.file.name)}"><figcaption>${esc(f.file.name)} · ${(f.file.size/1048576).toFixed(2)} MiB</figcaption>${btn('移除','remove-file',`data-index="${i}"`)}</figure>`).join('');};
  function add(incoming){const max=mode.value==='single'?1:10;if(files.length+incoming.length>max){toast(`当前模式最多 ${max} 张图片`);return;}for(const file of incoming){if(!['image/jpeg','image/png'].includes(file.type)||file.size>10*1048576){toast(file.name+'：仅支持不超过10MiB的 JPG / PNG');continue;}files.push({file,url:URL.createObjectURL(file),id:null,key:uuid()});}draw();}
  picker.onchange=()=>{add([...picker.files]);picker.value='';};zone.onclick=()=>picker.click();zone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();picker.click();}};zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag');};zone.ondragleave=()=>zone.classList.remove('drag');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag');add([...e.dataTransfer.files]);};
  ctx.dispose(()=>files.forEach(f=>URL.revokeObjectURL(f.url)));
  ctx.on('remove-file',b=>{const [f]=files.splice(+b.dataset.index,1);URL.revokeObjectURL(f.url);draw();});ctx.on('clear-files',()=>{files.forEach(f=>URL.revokeObjectURL(f.url));files=[];draw();});
  async function history(){if(!can('detection.read')){document.querySelector('#batch-history').innerHTML=empty('你拥有上传权限，但没有记录读取权限；请联系管理员调整权限组合。');return;}const data=await api('/detections/batches?page_size=10');if(!ctx.active())return;document.querySelector('#batch-history').innerHTML=data.items.map(x=>`<div class="toolbar"><span>${date(x.created_at)} · ${stateName[x.state]} · ${x.processed_count}/${x.total_count}</span>${btn('查看进度','open-batch',`data-id="${x.id}"`)}</div>`).join('')||empty('暂无批次');}
  async function progress(){if(!batch||!can('detection.read'))return;const data=await api('/detections/batches/'+batch,{background:true});if(!ctx.active())return;document.querySelector('#image-progress').innerHTML=`<p class="status-line">${stateName[data.state]} · 已处理 ${data.processed_count}/${data.total_count} · 命中图片 ${data.hit_image_count} · 失败 ${data.failed_count} · 取消 ${data.cancelled_count}</p>${data.state==='RUNNING'?btn(data.cancel_requested?'正在取消未执行项…':'取消未开始的图片','cancel-batch',data.cancel_requested?'disabled':''):''}${recordTable(data.items.filter(x=>!x.hidden))}`;}
  ctx.on('detect',async()=>{if(!files.length)throw new Error('请先选择图片');if(mode.value==='single'&&files.length!==1)throw new Error('单图模式只能提交一张');const status=document.querySelector('#image-progress');for(let i=0;i<files.length;i++){const f=files[i];if(f.id)continue;status.textContent=`正在校验上传 ${i+1}/${files.length}：${f.file.name}`;const body=new FormData();body.append('file',f.file);body.append('purpose','DETECTION_IMAGE');try{f.id=(await api('/media',{method:'POST',body,headers:{'Idempotency-Key':f.key}})).id;}catch(err){throw new Error(f.file.name+'：'+err.message+'；未创建本次检测任务。');}}
    if(mode.value==='single'){const item=await write('/detections/images',{media_id:files[0].id});status.innerHTML=can('detection.read')?`<p>任务已受理，状态 ${stateName[item.state]}</p>${nav('查看此任务','records/'+item.id)}`:empty('任务已受理；当前账户没有记录查询权限');files.forEach(f=>URL.revokeObjectURL(f.url));files=[];draw();}
    else{const data=await write('/detections/batches',{media_ids:files.map(x=>x.id)});batch=data.id;files.forEach(f=>URL.revokeObjectURL(f.url));files=[];draw();await progress();await history();}
  });ctx.on('open-batch',async b=>{batch=b.dataset.id;await progress();});ctx.on('cancel-batch',async()=>{await write('/detections/batches/'+batch+'/cancel');await progress();});await history();ctx.poll(progress,1200);
});

pages.set('camera',async ctx=>{
  let stream=null,session=null,seq=0,inFlight=false,last=null,closed=false,deviceList=[];
  ctx.set(card(`<div class="toolbar">${select('本机摄像头','camera-device',[['','默认设备']])}${field('采样尝试间隔（200–2000 ms）','interval',500,'number','min="200" max="2000" step="100"')}<div class="row">${btn('开始检测','start-camera','class="primary"')}${btn('暂停检测','pause-camera','disabled')}${btn('关闭摄像头','stop-camera','disabled')}</div></div><p id="camera-status" class="status-line">尚未开启摄像头</p><div class="grid two"><div class="camera-stage"><h3>实时预览（未叠加旧检测框）</h3><video id="camera-video" autoplay muted playsinline></video><span class="watermark">${esc(state.user.username)} · 企业演示</span></div><div><h3>最近送检帧及其对应结果</h3><canvas id="camera-result" class="result-canvas"></canvas><div id="camera-result-info"></div>${btn('保存当前结果帧','save-frame','disabled')}</div></div><p class="notice">默认每500ms尝试采样，仅一帧在途，不积压。暂停保留预览及心跳；关闭或离页释放设备。局域网摄像头必须通过可信 HTTPS 访问。</p>`));
  const video=document.querySelector('#camera-video'),resultCanvas=document.querySelector('#camera-result'),status=document.querySelector('#camera-status'),intervalInput=document.querySelector('[name=interval]');
  const control=()=>{document.querySelector('[data-action=start-camera]').disabled=!!session;document.querySelector('[data-action=pause-camera]').disabled=!session;document.querySelector('[data-action=pause-camera]').textContent=session?.state==='PAUSED'?'恢复检测':'暂停检测';document.querySelector('[data-action=stop-camera]').disabled=!session;document.querySelector('[data-action=save-frame]').disabled=!last||session?.state!=='ACTIVE';};
  async function stop(){closed=true;const old=session;session=null;last=null;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(video)video.srcObject=null;if(old)try{await write('/camera/sessions/'+old.id+'/stop');}catch(err){if(ctx.active())toast(err.message);}if(ctx.active()){status.textContent='摄像头已关闭，设备已释放';control();}}
  async function enumerate(){if(!navigator.mediaDevices)return;deviceList=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput');const chosen=document.querySelector('[name=camera-device]');if(chosen)chosen.innerHTML='<option value="">默认设备</option>'+deviceList.map((d,i)=>`<option value="${esc(d.deviceId)}">${esc(d.label||'摄像头 '+(i+1))}</option>`).join('');}
  await enumerate();ctx.dispose(()=>{closed=true;stop();});
  ctx.on('start-camera',async()=>{if(!navigator.mediaDevices?.getUserMedia)throw new Error('浏览器未开放摄像头接口，请使用 localhost 或可信 HTTPS。');const interval=Number(intervalInput.value);if(interval<200||interval>2000)throw new Error('采样间隔必须为200–2000ms');closed=false;const device=document.querySelector('[name=camera-device]').value;
    try{stream=await navigator.mediaDevices.getUserMedia({video:{...(device?{deviceId:{exact:device}}:{}),width:{ideal:1280},height:{ideal:720}},audio:false});if(!ctx.active()||closed){stream.getTracks().forEach(t=>t.stop());return;}video.srcObject=stream;await video.play();session=await write('/camera/sessions',{client_label:'浏览器本机摄像头',capture_interval_ms:interval});if(!ctx.active()||closed){await stop();return;}seq=0;last=null;status.textContent='采集中 · 送检帧结果在右侧显示';control();await enumerate();}catch(err){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;throw new Error(({NotAllowedError:'摄像头权限被拒绝，请在浏览器设置中允许',NotFoundError:'没有检测到摄像头',NotReadableError:'摄像头被占用或不可读取'})[err.name]||err.message);}
  });
  ctx.on('pause-camera',async()=>{if(!session)return;last=null;control();const action=session.state==='PAUSED'?'resume':'pause';session=await write(`/camera/sessions/${session.id}/${action}`,{generation:session.generation,...(action==='resume'?{capture_interval_ms:Number(intervalInput.value)}:{})});last=null;resultCanvas.getContext('2d').clearRect(0,0,resultCanvas.width,resultCanvas.height);status.textContent=session.state==='PAUSED'?'检测已暂停；实时预览和心跳继续':'已恢复，等待新代帧';control();});ctx.on('stop-camera',stop);
  ctx.on('save-frame',async()=>{if(!last||!session)throw new Error('没有可保存的有效结果帧');const data=await write(`/camera/sessions/${session.id}/snapshots`,{frame_id:last.frame_id,generation:session.generation});toast('已保存结果帧 '+data.id);});
  let nextAt=0;
  ctx.poll(async()=>{if(!session||session.state!=='ACTIVE'||inFlight||closed||!video.videoWidth||Date.now()<nextAt)return;inFlight=true;nextAt=Date.now()+session.capture_interval_ms;const current=session.id,generation=session.generation;
    try{const canvas=document.createElement('canvas'),scale=Math.min(1,1280/video.videoWidth,720/video.videoHeight);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);const sourceContext=canvas.getContext('2d');sourceContext.drawImage(video,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));const body=new FormData();body.append('file',blob,'frame.jpg');body.append('frame_seq',String(++seq));body.append('generation',String(generation));const data=await api(`/camera/sessions/${current}/frames`,{method:'POST',body,background:true});if(!ctx.active()||closed||session?.id!==current||session.generation!==generation||session.state!=='ACTIVE')return;last=data;resultCanvas.width=canvas.width;resultCanvas.height=canvas.height;const c=resultCanvas.getContext('2d');c.drawImage(canvas,0,0);c.lineWidth=3;c.strokeStyle='#ff4242';c.fillStyle='#ff5353';c.font='16px sans-serif';data.boxes.forEach(b=>{const [x1,y1,x2,y2]=b.bbox;c.strokeRect(x1,y1,x2-x1,y2-y1);c.fillText(`${b.class_name} ${b.confidence.toFixed(3)}`,x1,Math.max(18,y1-5));});const detectedLabels=labels(data.boxes);document.querySelector('#camera-result-info').innerHTML=`<p>帧 ${data.frame_seq} · ${data.boxes.length?`检出 ${data.boxes.length} 个框（${esc(detectedLabels.join('、'))}），需复核`:'未检出模型目标'} · ${data.inference_ms}ms</p><p class="muted">${{SAVED:'结果已留档',COOLDOWN:'冷却期未自动保存，可手动保存',FAILED:'结果未留档，请检查存储服务',NOT_REQUIRED:'未自动保存，可手动保存'}[data.persist_status]} · 有效至 ${date(data.result_expires_at)}</p>`;control();}
    catch(err){if(ctx.active()&&!closed&&!['STALE_CAMERA_GENERATION','CAMERA_PAUSED','INFERENCE_QUEUE_FULL','FRAME_IN_FLIGHT'].includes(err.code))status.textContent=err.message;}finally{inFlight=false;}
  },200);
  ctx.poll(async()=>{if(session)await write(`/camera/sessions/${session.id}/heartbeat`,{},'POST',{background:true});},15000);
});
